###
##
# Database of reports, pins
MySQL:
  host: 'localhost'
  port: '3306'
  database: 'mydb'
  username: 'root'
  password: ''

###
##
# No permission message
No Permission: '&c&lHey &fyou dont have permission to do that'

###
##
# Chat Control

ChatControl:
# slow chat ( seconds )
  default: 0
  message: '&cYou can chat again in &6{cooldown} &csecond(s)'

###
##
# Staff Vanish
Staff Vanish:
  invisibility: true
  hide-message: '&aYou have been vanished'
  show-message: '&aYou are no longer vanished'

###
##
# Inventory Revive
Restore Inventory:
   message: '&6/revive: &fto restore your inventory'
   unavailable: '&c&lHey &fyou have no inventory to restore'
   success: '&aSuccessfully restored inventory'

###
##
# Clicks Per Second
CPS:
  left_click_only: true
  warning: 8
  warning_prefix: '&4&lWarning &e'

###
##
# Auth Pin
Auth Pin:
   numbers: 'cyan wool'
   name: '&c{name}'
   login: 'furnace'
   register: 'furnace'
   placeholder: 'black stained glass pane'
   login_after_register: true
   eraser: tnt
   max_attempt: 4

###
##
# Random Teleport
Random Teleport:

   biome_blacklist:
      - 'ocean'
      - 'river'
      - 'deep ocean'

   block_blacklist:
      - 'cactus'