name: Staff
version: ${project.version}
main: com.vanquil.staff.Staff
api-version: 1.16
commands:
   slowchat:
      description: slows chat
      aliases: [chatslow]
   unslow:
      description: unslow chat
   freeze:
      description: freeze command
