name: VanquilStaff
version: ${project.version}
main: com.vanquil.staff.Staff
api-version: 1.16
commands:
   slowchat:
      description: slows chat
      aliases: [chatslow]
   unslow:
      description: unslow chat
   freeze:
      description: freeze command
   falerts:
      description: toggle filter alerts
   filter:
      description: toggle filter system
   blacklist:
      description: blacklist a player
   revive:
      description: restore the inventory
      aliases: [invrestore]
   vanish:
      description: allow you to hide
      aliases: [v, hidestaff]
   staffs:
      description: check all available staffs
      aliases: [slist, stafflist, onlinestaff]
   cps:
      description: check all of cps
      aliases: [cpsreport]
   report:
      description: report a player